server:
  port: 9001

spring:
  application:
    name: ${APP_NAME:myjob-executor-sample-springboot}


myjob:
  scheduler:
    protocal: http
    endpoint: ${MYJOB_SCHEDULER_ENDPOINT:192.168.3.27:7001}
