server:
  port: 7001

spring:
  profiles:
    active: local
  application:
    name: myjob-scheduler
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/pages/
    suffix: .html